spring.application.name=report-service
server.port=8084

# JWT — mesmo segredo do user-service
app.jwt.secret=3cFqr9Xv8pNzLmKwEoJbDsYtAhUgRiPl2nVxOzBmQkHyWdCu
app.jwt.expiration-ms=86400000

# Endereco do order-service (HTTP) — report-service nao tem banco proprio,
# toda a agregacao parte dos dados obtidos aqui.
services.order-service.base-url=http://localhost:8083
