spring.application.name=order-service
server.port=8083

spring.datasource.url=jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT — mesmo segredo do user-service
app.jwt.secret=3cFqr9Xv8pNzLmKwEoJbDsYtAhUgRiPl2nVxOzBmQkHyWdCu
app.jwt.expiration-ms=86400000

# Endereco do product-service (HTTP) — unica forma de order-service enxergar produtos/estoque
services.product-service.base-url=http://localhost:8082
